from __future__ import annotations

import json
import shutil
import subprocess
import sys
import tempfile
import unittest
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SCRIPT = ROOT / "codex_orch_tools.py"
FIXTURE = ROOT / "tests" / "replay" / "long-run-001"
HANDOFF_HEADINGS = (
    "## Status",
    "## Summary",
    "## Files Changed",
    "## Claims / Findings",
    "## Commands Reported",
    "## Caveats / Blockers",
)


def run_cli(*args: str) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        [sys.executable, str(SCRIPT), *args],
        check=False,
        text=True,
        capture_output=True,
        cwd=ROOT,
    )


def journal_entries(run_dir: Path) -> list[dict[str, object]]:
    return [
        json.loads(line)
        for line in (run_dir / "journal.jsonl").read_text(encoding="utf-8").splitlines()
        if line.strip()
    ]


class PromptFirstWorkflowTests(unittest.TestCase):
    @classmethod
    def setUpClass(cls) -> None:
        cls.temp_dir = tempfile.TemporaryDirectory()
        cls.run_dir = Path(cls.temp_dir.name) / "long-run-001"
        shutil.copytree(FIXTURE, cls.run_dir)
        cls.launches: list[subprocess.CompletedProcess[str]] = []

        for execution in (
            record for record in journal_entries(cls.run_dir) if record["type"] == "execution"
        ):
            prompt_path = cls.run_dir / str(execution["prompt"])
            events_path = cls.run_dir / str(execution["events"])
            handoff_path = cls.run_dir / str(execution["handoff"])
            if events_path.exists() or handoff_path.exists():
                raise AssertionError("fake Codex outputs must be generated by the test launch")
            with (
                prompt_path.open("r", encoding="utf-8") as prompt,
                events_path.open("w", encoding="utf-8") as events,
            ):
                result = subprocess.run(
                    [
                        sys.executable,
                        str(cls.run_dir / "fake_codex.py"),
                        "exec",
                        "--json",
                        "--output-last-message",
                        str(handoff_path),
                    ],
                    check=False,
                    text=True,
                    stdin=prompt,
                    stdout=events,
                    stderr=subprocess.PIPE,
                    cwd=cls.run_dir,
                )
            if result.returncode != 0:
                raise AssertionError(result.stderr)
            cls.launches.append(result)

        evidence_path = cls.run_dir / "evidence" / "unit-tests.txt"
        if evidence_path.exists():
            raise AssertionError("fake evidence must be generated by the test check")
        evidence = subprocess.run(
            [
                sys.executable,
                "-m",
                "unittest",
                "discover",
                "-s",
                "tests",
                "-p",
                "test_example.py",
                "-q",
            ],
            check=False,
            text=True,
            capture_output=True,
            cwd=cls.run_dir,
        )
        if evidence.returncode != 0:
            raise AssertionError(evidence.stdout + evidence.stderr)
        evidence_path.parent.mkdir(parents=True, exist_ok=True)
        evidence_path.write_text(evidence.stdout + evidence.stderr, encoding="utf-8")

    @classmethod
    def tearDownClass(cls) -> None:
        cls.temp_dir.cleanup()

    def test_fake_exec_captures_two_named_agent_executions_and_handoffs(self) -> None:
        records = journal_entries(self.run_dir)
        run_started = records[0]
        executions = [record for record in records if record["type"] == "execution"]

        self.assertTrue(Path(str(run_started["repo"])).is_absolute())
        self.assertTrue(run_started["goal"])
        self.assertEqual(len(str(run_started["repo_head"])), 40)
        self.assertEqual(run_started["repo_status"], [])
        self.assertEqual(len(self.launches), 2)
        self.assertEqual(
            {(record["agent"], record["execution"]) for record in executions},
            {
                ("codex-impl-01", "execution-01"),
                ("codex-review-01", "execution-01"),
            },
        )
        for execution in executions:
            self.assertTrue(Path(str(execution["worktree"])).is_absolute())
            self.assertEqual(len(str(execution["head"])), 40)
            self.assertTrue(execution["branch"])
            prompt = (self.run_dir / str(execution["prompt"])).read_text(encoding="utf-8")
            self.assertEqual(
                tuple(line for line in prompt.splitlines() if line.startswith("## ")),
                HANDOFF_HEADINGS,
            )
            self.assertTrue((self.run_dir / str(execution["events"])).is_file())
            handoff = (self.run_dir / str(execution["handoff"])).read_text(encoding="utf-8")
            self.assertEqual(
                tuple(line for line in handoff.splitlines() if line.startswith("## ")),
                HANDOFF_HEADINGS,
            )

        verifications = [record for record in records if record["type"] == "verification"]
        evidence_paths = [
            self.run_dir / str(path)
            for verification in verifications
            for path in verification.get("evidence", [])
        ]
        self.assertTrue(evidence_paths)
        self.assertTrue(all(path.is_file() for path in evidence_paths))
        self.assertTrue((self.run_dir / "src/example.py").is_file())
        self.assertTrue((self.run_dir / "tests/test_example.py").is_file())
        self.assertFalse(any(record["type"] == "decision" for record in records))
        self.assertEqual(records[-1]["type"], "run_closed")
        self.assertEqual(records[-1]["judgment"], "passed")
        self.assertFalse((self.run_dir / "report.md").exists())

    def test_tools_read_both_fake_codex_streams(self) -> None:
        records = journal_entries(self.run_dir)
        executions = [record for record in records if record["type"] == "execution"]

        for execution in executions:
            result = run_cli(
                "state",
                str(execution["agent"]),
                "--file",
                str(self.run_dir / str(execution["events"])),
                "--json",
            )
            self.assertEqual(result.returncode, 0, result.stderr)
            payload = json.loads(result.stdout)
            self.assertEqual(payload["status"], "complete")
            handoff = (self.run_dir / str(execution["handoff"])).read_text(encoding="utf-8")
            self.assertEqual(payload["details"]["last_agent_message"].strip(), handoff.strip())

    def test_monitor_watches_both_in_flight_executions(self) -> None:
        with tempfile.TemporaryDirectory() as tmp_dir:
            root = Path(tmp_dir)
            run_dir = root / ".codex-consult" / "runs" / "long-run-001"
            shutil.copytree(self.run_dir, run_dir)
            records = journal_entries(run_dir)
            launch_records = [
                record
                for record in records
                if record["type"] in {"run_started", "task", "execution"}
                and not (record["type"] == "task" and record.get("status") != "active")
            ]
            (run_dir / "journal.jsonl").write_text(
                "".join(
                    json.dumps(record, separators=(",", ":")) + "\n"
                    for record in launch_records
                ),
                encoding="utf-8",
            )

            result = run_cli(
                "monitor",
                "--repo",
                str(root),
                "--run-id",
                "long-run-001",
                "--once",
            )

        self.assertEqual(result.returncode, 0, result.stderr)
        notifications = [json.loads(line) for line in result.stdout.splitlines() if line.strip()]
        completed = [
            notification
            for notification in notifications
            if notification.get("type") == "codex_agent_complete"
        ]
        self.assertEqual(len(completed), 2, notifications)
        self.assertEqual(
            {Path(str(notification["path"])).parent.parent.name for notification in completed},
            {"codex-impl-01", "codex-review-01"},
        )

    def test_validation_accepts_the_closed_fixture(self) -> None:
        result = run_cli("validate", str(self.run_dir))

        self.assertEqual(result.returncode, 0, result.stderr)
        payload = json.loads(result.stdout)
        self.assertTrue(payload["ok"], payload)
        self.assertEqual(payload["issues"], [])
        self.assertEqual(payload["non_passing_verifications"], [])


if __name__ == "__main__":
    unittest.main()
